#!/bin/bash

set -e

VERSION=$(cat Dockerfile | grep '^ENV VERSION' | cut -d" " -f3)

re='^[0-9]+([.][0-9]+)?$'
if [[ $CACHE_TAG =~ $re ]] ; then
  echo "CACHE_TAG=$CACHE_TAG"
  echo "===> Retagging $IMAGE_NAME"
  docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION
  echo "===> Pushing $DOCKER_REPO:$VERSION"
  docker push $DOCKER_REPO:$VERSION
fi
